from typing import Any
from .memory import Memory

class Allocator:
    def allocate(self, nbytes : int, stream = 0) -> Memory: ...

    def free(self, mem : Memory) -> None: ...

    def memory_stats(self) -> Any: ...

    def free_all(self): ...
